#markdown: rdiscount
markdown: kramdown
toc_levels: 1..2
permalink: /:year/:month/:title/
url: http://hitdong.github.io
author: Dong
author.avatar: false
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
paginate: 24
